spring:
  profiles:
    active: dev

  application:
    name: bio-code

  threads:
    virtual:
      enabled: true

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.10.202:3306/endpoint_analysis_service_test?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #username: root
    #password: root

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/endpoint_analysis_service?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:tcp://127.0.0.1:59000/./EndpointAnalysisService
    #username:
    #password:

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  data:
    jpa:
      repositories:
        bootstrap-mode: lazy

  jpa:
    show-sql: false
    hibernate:
      #ddl-auto: update
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.MySQLDialect


  main:
    lazy-initialization: true

  quartz:
    auto-startup: false
    job-store-type: jdbc
    jdbc:
      initialize-schema: never

  flyway:
    enabled: true
    locations: classpath:sql/automatic
    baseline-on-migrate: true
    baseline-version: 1.5.23
    baseline-description: "Baseline1.5W"

server:
  port: 27500

session:
  expires: 86400

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: false
    path: /swagger-ui
    display-request-duration: true
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha

application:
  version: 1.5SCP18 # 应用版本号

#附件模块配置
module-attach:
  #默认存储类型
  default: LOCAL

  #本地文件存储配置
  local:
    linux: /eas
    windows: C:\EAS
    auto-create: true

#驱动器模块配置
module-drive:
  #签名SecretKey
  sign-secret-key: 550e8400-e29b-41d4-a716-446655440000-7c9e6679-7425-40de-944b-e07fc1f90ae7-6ba7b810-9dad-11d1-80b4-00c04fd430c8

  #签名有效时间(秒)
  ttl: 3600

#审计模块配置
audit:
  #是否记录系统错误记录
  record-error-rcd: true

#应用状态监控模块配置
module-app-status:
  #后台采样间隔（毫秒），前端轮询频率建议 >= 此值
  sample-delay-ms: 1000

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
#logging:
#  level:
#    org.springframework.boot.context.logging: INFO
#    # 开启 Spring Bean 初始化的详细日志
#    org.springframework.beans.factory.support.DefaultListableBeanFactory: DEBUG


# 行为验证码配置， 详细请看 cloud.tianai.captcha.autoconfiguration.ImageCaptchaProperties 类
captcha:
  # 如果项目中使用到了redis，滑块验证码会自动把验证码数据存到redis中， 这里配置redis的key的前缀,默认是captcha:slider
  prefix: captcha
  # 验证码过期时间，默认是2分钟,单位毫秒， 可以根据自身业务进行调整
  expire:
    # 默认缓存时间 2分钟
    default: 10000
    # 针对 点选验证码 过期时间设置为 2分钟， 因为点选验证码验证比较慢，把过期时间调整大一些
    WORD_IMAGE_CLICK: 20000
  # 使用加载系统自带的资源， 默认是 false(这里系统的默认资源包含 滑动验证码模板/旋转验证码模板,如果想使用系统的模板，这里设置为true)
  init-default-resource: true
  # 缓存控制， 默认为false不开启
  local-cache-enabled: false
  # 缓存开启后，验证码会提前缓存一些生成好的验证数据， 默认是20
  local-cache-size: 20
  # 缓存开启后，缓存拉取失败后等待时间 默认是 5秒钟
  local-cache-wait-time: 5000
  # 缓存开启后，缓存检查间隔 默认是2秒钟
  local-cache-period: 2000
  # 缓存开启后，忽略的字段，默认是 ""(不忽略任何字段)
  local-cache-ignored-cache-fields: ""
  # 配置字体包，供文字点选验证码使用,可以配置多个，不配置使用默认的字体
  font-path:
    - classpath:font/SimHei.ttf
  secondary:
    # 二次验证， 默认false 不开启
    enabled: false
    # 二次验证过期时间， 默认 2分钟
    expire: 120000
    # 二次验证缓存key前缀，默认是 captcha:secondary
    keyPrefix: "captcha:secondary"