spring:
  profiles:
    active: dev

  application:
    name: endpoint-relay-service

  threads:
    virtual:
      enabled: true
  
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.202:3306/endpoint_analysis_service_test?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/endpoint_analysis_service?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #username: root
    #password: root

    #driver-class-name: org.h2.Driver
    #url: jdbc:h2:tcp://127.0.0.1:59000/./EndpointAnalysisService
    #username:
    #password:

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: false

  thymeleaf:
    cache: false  # 开发环境禁用模板缓存
    prefix: classpath:/views/
    suffix: .html

server:
  port: 27500

session:
  expires: 86400

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    try-it-out-enabled: true
    operations-sorter: alpha
    tags-sorter: alpha

knife4j:
  enable: true

application:
  version: 1.2G # 应用版本号
